// import type { NextPage } from "next"
// import Head from "next/head"
// import styles from "../styles/Home.module.css"
// import dynamic from "next/dynamic"
// import { utils } from "@worldcoin/id"
// import { WidgetProps } from "@worldcoin/id"
// import { useEffect } from "react"
// import { keccak256 } from "@ethersproject/solidity"
// import { ethers } from "ethers"
// import axios from "axios"

// // export default Home;
// // import type { NextPage } from "next";
// // import Head from "next/head";
// // import styles from "../styles/Home.module.css";
// // import dynamic from "next/dynamic";
// // import { utils } from "@worldcoin/id";
// // import { WidgetProps } from "@worldcoin/id";
// // import { useEffect } from "react";
// // import { keccak256 } from "@ethersproject/solidity";
// // import {ethers} from 'ethers'
// // import axios from "axios";

// // const WorldIDWidget = dynamic<WidgetProps>(
// //   () => import("@worldcoin/id").then((mod) => mod.WorldIDWidget),
// //   { ssr: false }
// // );
// // let signalHash = keccak256(
// //   ["uint256"],
// //   [18179]
// // )
// // let signal2 = BigInt(signalHash) >> BigInt(8);
// //  let signal3 = signal2.toString();

// //  let signalHash2 = keccak256(
// //   ["string"],
// //   ["wid_staging_2ef14547b3882ab92e3ed9ce378062f7"]
// // )
// // let signal22 = BigInt(signalHash2) >> BigInt(8);
// //  let signal32 = signal22.toString();
// //  console.log(signal32, "   profis", signal3)
// // const widgetProps: WidgetProps = {
// //   // enableTelemetry: true,
// //   // actionId: "wid_staging_73d604ee0b72c4c7e660a418ee130b6a",
// //   // signal: "yourSignal", // <- Set an appropriate signal for each user

// //   actionId: "wid_staging_2ef14547b3882ab92e3ed9ce378062f7",
// //   signal: signal2,

// //   enableTelemetry: true,
// //   appName: "test",
// //   signalDescription: "test",
// //   theme: "dark",
// //   advancedUseRawSignal: true,
// //   debug: true, // Recommended **only** for development
// //   onSuccess: (result) => console.log(result),
// //   onError: ({ code, detail }) => console.log({ code, detail }),

// //   onInitSuccess: () => console.log("Init successful"),
// //   onInitError: (error) => console.log("Error while initialization World ID", error),
// // };

// // const Home: NextPage = () => {
// //   useEffect(() => {
// //     console.log("Random Number from utils: ", utils.randomNumber(1, 100));
// //   }, []);
// //   const decode = ( hash: string) => {
// //     const unpackedProof = ethers.utils.defaultAbiCoder.decode(
// //         ["uint256[8]"],
// //        hash
// //     )[0]
// //     console.log(unpackedProof)
// //   let array = []
// //   for(let i=0; i < 8;i++){
// //     array.push(unpackedProof[i]._hex)
// //   }
// //   console.log(array)
// //   return array
// // }
// // const  sendReq = async (data : any) => {
// //   const res = await axios.post('https://developer.worldcoin.org/api/v1/verify',
// //   data, {
// //     headers: {
// //       "Content-Type": "application/json"
// //   }
// //   });

// //   console.log(res); // text/json
// // }
// //   return (
// //     <div className={styles.container}>
// //       <Head>
// //         <title>Create Next App</title>
// //         <meta name="description" content="Generated by create next app" />
// //         <link rel="icon" href="/favicon.ico" />
// //       </Head>

// //       <main className={styles.main}>
// //       <WorldIDWidget
// //   actionId="wid_staging_3b9e688b2f1b9fa2957249b3df8edb9f" // obtain this from developer.worldcoin.org
// //   signal= "123"
// //   enableTelemetry
// //   onSuccess={(verificationResponse) => {console.log(verificationResponse);sendReq(  {
// //     "action_id": "wid_staging_3b9e688b2f1b9fa2957249b3df8edb9f",
// //     "signal": "123",
// //     "proof": verificationResponse.proof,
// //     "nullifier_hash": verificationResponse.nullifier_hash,
// //     "merkle_root": verificationResponse.merkle_root
// // }) }
// // }
// //   onError={(error) => console.error(error)}
// // />;
// //    </main>
// //     </div>
// //   );
// // };

// // export default Home;

// const WorldIDWidget =
//     dynamic <
//     WidgetProps >
//     (() => import("@worldcoin/id").then((mod) => mod.WorldIDWidget), { ssr: false })
// // let signalHash = keccak256(
// //   ["uint256"],
// //   [18179]
// // )
// // let signal2 = BigInt(signalHash) >> BigInt(8);
// //  let signal3 = signal2.toString();

// //  let signalHash2 = keccak256(
// //   ["string"],
// //   ["wid_staging_2ef14547b3882ab92e3ed9ce378062f7"]
// // )
// // let signal22 = BigInt(signalHash2) >> BigInt(8);
// //  let signal32 = signal22.toString();
// //  console.log(signal32, "   profis", signal3)
// // const widgetProps: WidgetProps = {
// // enableTelemetry: true,
// // actionId: "wid_staging_73d604ee0b72c4c7e660a418ee130b6a",
// // signal: "yourSignal", // <- Set an appropriate signal for each user

// //   actionId: "wid_staging_2ef14547b3882ab92e3ed9ce378062f7",
// //   signal: signal2,

// //   enableTelemetry: true,
// //   appName: "test",
// //   signalDescription: "test",
// //   theme: "dark",
// //   advancedUseRawSignal: true,
// //   debug: true, // Recommended **only** for development
// //   onSuccess: (result) => console.log(result),
// //   onError: ({ code, detail }) => console.log({ code, detail }),

// //   onInitSuccess: () => console.log("Init successful"),
// //   onInitError: (error) => console.log("Error while initialization World ID", error),
// // };

// const Home: NextPage = () => {
//     //   useEffect(() => {
//     //     console.log("Random Number from utils: ", utils.randomNumber(1, 100));
//     //   }, []);
//     const decode = (hash: string) => {
//         const unpackedProof = ethers.utils.defaultAbiCoder.decode(["uint256[8]"], hash)[0]
//         console.log(unpackedProof)
//         let array = []
//         for (let i = 0; i < 8; i++) {
//             array.push(unpackedProof[i]._hex)
//         }
//         console.log(array)
//         return array
//     }
//     // const  sendReq = async (data : any) => {
//     //   const res = await axios.post('https://developer.worldcoin.org/api/v1/verify',
//     //   data, {
//     //     headers: {
//     //       "Content-Type": "application/json"
//     //   }
//     //   });

//     //   console.log(res); // text/json
//     // }
//     return (
//         <div className={styles.container}>
//             <Head>
//                 <title>Create Next App</title>
//                 <meta name="description" content="Generated by create next app" />
//                 <link rel="icon" href="/favicon.ico" />
//             </Head>

//             <main className={styles.main}>
//                 <WorldIDWidget
//                     actionId="wid_staging_2ef14547b3882ab92e3ed9ce378062f7" // obtain this from developer.worldcoin.org
//                     signal="123"
//                     enableTelemetry
//                     onSuccess={(verificationResponse) => {
//                         console.log(verificationResponse)
//                         sendReq({
//                             action_id: "wid_staging_3b9e688b2f1b9fa2957249b3df8edb9f",
//                             signal: "123",
//                             proof: decode(verificationResponse.proof),
//                             nullifier_hash: verificationResponse.nullifier_hash,
//                             merkle_root: verificationResponse.merkle_root,
//                         })
//                     }}
//                     onError={(error) => console.error(error)}
//                 />
//                 ;
//             </main>
//         </div>
//     )
// }
